import type { Song, Artist, Playlist, Genre, Ad } from "./types"

export const mockSongs: Song[] = [
  {
    id: "1",
    title: "ချစ်သူ",
    artist: "Sai Sai Kham Leng",
    album: "Love Songs Collection",
    duration: 245,
    coverUrl: "/myanmar-traditional-music-album-cover-with-golden-.jpg",
    audioUrl: "/audio/song1.mp3",
    genre: "Pop",
    isPremium: false,
    lyrics: [
      { time: 0, text: "နေ့တိုင်း မင်းကို တွေးမိတယ်", translation: "Every day I think of you" },
      { time: 5, text: "အိပ်မက်ထဲမှာပါ မင်းပဲ", translation: "Even in my dreams, it's you" },
      { time: 10, text: "ချစ်သူ... ချစ်သူ...", translation: "My love... My love..." },
      { time: 15, text: "မင်းမရှိရင် ငါ မနေနိုင်ဘူး", translation: "I can't live without you" },
      { time: 20, text: "အချိန်တွေ ကုန်သွားပေမယ့်", translation: "Even as time passes" },
      { time: 25, text: "ငါ့ရင်ထဲမှာ မင်းပဲ ရှိတယ်", translation: "You're still in my heart" },
    ],
  },
  {
    id: "2",
    title: "မြန်မာပြည်",
    artist: "Phyu Phyu Kyaw Thein",
    album: "Homeland",
    duration: 312,
    coverUrl: "/myanmar-landscape-album-cover-with-bagan-temples-s.jpg",
    audioUrl: "/audio/song2.mp3",
    genre: "Traditional",
    isPremium: false,
    lyrics: [
      { time: 0, text: "မြန်မာပြည် ရွှေပြည်တော်", translation: "Myanmar, the Golden Land" },
      { time: 6, text: "ငါတို့ မွေးဖွားရာ တိုင်းပြည်", translation: "The country where we were born" },
      { time: 12, text: "ရွှေစေတီ တွေလည်း တောက်ပနေ", translation: "Golden pagodas shining bright" },
      { time: 18, text: "အေးချမ်းသာယာ လှပတဲ့ပြည်", translation: "A peaceful and beautiful land" },
    ],
  },
  {
    id: "3",
    title: "အချစ်စစ်",
    artist: "Hlwan Paing",
    album: "True Love",
    duration: 278,
    coverUrl: "/romantic-myanmar-music-album-with-lotus-flowers.jpg",
    audioUrl: "/audio/song3.mp3",
    genre: "Rock",
    isPremium: true,
    lyrics: [
      { time: 0, text: "မင်းကို ချစ်တယ် ဆိုတာ", translation: "When I say I love you" },
      { time: 5, text: "အမှန်တရားပဲ ဖြစ်တယ်", translation: "It's nothing but the truth" },
      { time: 10, text: "ငါ့နှလုံးသား အားလုံး", translation: "My entire heart" },
      { time: 15, text: "မင်းအတွက်ပဲ ခုတယ်", translation: "Beats only for you" },
    ],
  },
  {
    id: "4",
    title: "ညီလေး",
    artist: "Ni Ni Khin Zaw",
    album: "Family Bonds",
    duration: 198,
    coverUrl: "/myanmar-family-themed-album-cover-warm-colors.jpg",
    audioUrl: "/audio/song4.mp3",
    genre: "Folk",
    isPremium: false,
    lyrics: [
      { time: 0, text: "ညီလေးရေ လာခဲ့ပါ", translation: "Little brother, come here" },
      { time: 5, text: "အမ ပြောပြမယ်", translation: "Big sister will tell you" },
      { time: 10, text: "ဘဝမှာ ကြိုးစားပါ", translation: "Work hard in life" },
    ],
  },
  {
    id: "5",
    title: "မိုးရွာနေပြီ",
    artist: "R Zar Ni",
    album: "Rainy Season",
    duration: 267,
    coverUrl: "/myanmar-monsoon-rain-artistic-album-cover.jpg",
    audioUrl: "/audio/song5.mp3",
    genre: "Hip Hop",
    isPremium: true,
    lyrics: [
      { time: 0, text: "မိုးရွာနေပြီ အပြင်မှာ", translation: "It's raining outside" },
      { time: 5, text: "မင်းကို သတိရမိတယ်", translation: "I remember you" },
      { time: 10, text: "အဲ့တုန်းက ကျွန်တော်တို့", translation: "Back then, we" },
      { time: 15, text: "အတူတူ လမ်းလျှောက်ခဲ့တယ်", translation: "Walked together" },
    ],
  },
  {
    id: "6",
    title: "နွေဦးသီချင်း",
    artist: "Wai La",
    album: "Spring Melodies",
    duration: 234,
    coverUrl: "/myanmar-spring-flowers-padauk-blossoms-album.jpg",
    audioUrl: "/audio/song6.mp3",
    genre: "Pop",
    isPremium: false,
    lyrics: [
      { time: 0, text: "နွေဦးရောက်လာပြီ", translation: "Spring has arrived" },
      { time: 5, text: "ပန်းတွေ ပွင့်နေပြီ", translation: "Flowers are blooming" },
    ],
  },
  {
    id: "7",
    title: "သင်္ကြန်မိုး",
    artist: "Lay Phyu",
    album: "Festival Songs",
    duration: 289,
    coverUrl: "/myanmar-thingyan-water-festival-celebration-album.jpg",
    audioUrl: "/audio/song7.mp3",
    genre: "Rock",
    isPremium: false,
    lyrics: [
      { time: 0, text: "သင်္ကြန်မိုး ရွာနေပြီ", translation: "Thingyan rain is falling" },
      { time: 5, text: "ပျော်ရွှင်စရာ အချိန်", translation: "A time for joy" },
    ],
  },
  {
    id: "8",
    title: "ဒဏ်ရာ",
    artist: "Sai Sai Kham Leng",
    album: "Wounds",
    duration: 256,
    coverUrl: "/emotional-myanmar-ballad-album-dark-moody.jpg",
    audioUrl: "/audio/song8.mp3",
    genre: "Ballad",
    isPremium: true,
    lyrics: [
      { time: 0, text: "ဒဏ်ရာတွေ ကျန်ခဲ့ပြီ", translation: "Wounds remain" },
      { time: 5, text: "ပျောက်ကင်းဖို့ ခက်တယ်", translation: "Hard to heal" },
    ],
  },
]

export const mockArtists: Artist[] = [
  {
    id: "1",
    name: "Sai Sai Kham Leng",
    imageUrl: "/myanmar-male-singer-portrait-artistic.jpg",
    bio: "One of Myanmar's most beloved pop artists, known for emotional ballads and contemporary hits.",
    monthlyListeners: 1250000,
    genres: ["Pop", "Ballad"],
  },
  {
    id: "2",
    name: "Phyu Phyu Kyaw Thein",
    imageUrl: "/myanmar-female-traditional-singer-elegant.jpg",
    bio: "Legendary Myanmar vocalist celebrated for traditional and patriotic songs.",
    monthlyListeners: 890000,
    genres: ["Traditional", "Folk"],
  },
  {
    id: "3",
    name: "Hlwan Paing",
    imageUrl: "/myanmar-rock-musician-portrait-cool.jpg",
    bio: "Rock icon known for powerful vocals and energetic performances.",
    monthlyListeners: 720000,
    genres: ["Rock", "Pop"],
  },
  {
    id: "4",
    name: "Ni Ni Khin Zaw",
    imageUrl: "/myanmar-female-folk-singer-warm-smile.jpg",
    bio: "Folk music treasure preserving Myanmar's musical heritage.",
    monthlyListeners: 540000,
    genres: ["Folk", "Traditional"],
  },
  {
    id: "5",
    name: "R Zar Ni",
    imageUrl: "/myanmar-hip-hop-artist-modern-urban-style.jpg",
    bio: "Pioneer of Myanmar hip hop scene with socially conscious lyrics.",
    monthlyListeners: 980000,
    genres: ["Hip Hop", "Rap"],
  },
  {
    id: "6",
    name: "Wai La",
    imageUrl: "/myanmar-pop-singer-young-trendy.jpg",
    bio: "Rising star known for catchy pop melodies and youthful energy.",
    monthlyListeners: 650000,
    genres: ["Pop", "Dance"],
  },
  {
    id: "7",
    name: "Lay Phyu",
    imageUrl: "/myanmar-rock-legend-iconic-pose.jpg",
    bio: "The godfather of Myanmar rock music with decades of hits.",
    monthlyListeners: 1100000,
    genres: ["Rock", "Alternative"],
  },
]

export const mockGenres: Genre[] = [
  {
    id: "1",
    name: "Pop",
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Contemporary Myanmar pop music",
  },
  {
    id: "2",
    name: "Traditional",
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Classic Myanmar traditional music",
  },
  {
    id: "3",
    name: "Rock",
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Myanmar rock and alternative",
  },
  {
    id: "4",
    name: "Folk",
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Regional folk songs of Myanmar",
  },
  {
    id: "5",
    name: "Hip Hop",
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Myanmar hip hop and rap",
  },
  {
    id: "6",
    name: "Ballad",
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "Emotional love songs",
  },
]

export const mockPlaylists: Playlist[] = [
  {
    id: "1",
    name: "Myanmar Classics",
    description: "Timeless hits from Myanmar's golden era",
    coverUrl: "/placeholder.svg?height=300&width=300",
    songs: mockSongs.slice(0, 4),
    createdBy: "Myanify",
    isPublic: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Thingyan Vibes",
    description: "Water festival celebration songs",
    coverUrl: "/placeholder.svg?height=300&width=300",
    songs: mockSongs.slice(2, 6),
    createdBy: "Myanify",
    isPublic: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "3",
    name: "Late Night Myanmar",
    description: "Soulful songs for quiet evenings",
    coverUrl: "/placeholder.svg?height=300&width=300",
    songs: mockSongs.slice(1, 5),
    createdBy: "Myanify",
    isPublic: true,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "4",
    name: "Myanmar Rock Anthems",
    description: "The best of Myanmar rock",
    coverUrl: "/placeholder.svg?height=300&width=300",
    songs: mockSongs.filter((s) => s.genre === "Rock"),
    createdBy: "Myanify",
    isPublic: true,
    createdAt: new Date("2024-04-10"),
  },
]

export const mockAds: Ad[] = [
  {
    id: "1",
    title: "Experience Bagan",
    description: "Discover the ancient temples of Myanmar",
    imageUrl: "/placeholder.svg?height=100&width=300",
    linkUrl: "#",
    sponsor: "Myanmar Tourism",
  },
  {
    id: "2",
    title: "KBZ Bank",
    description: "Banking made simple for everyone",
    imageUrl: "/placeholder.svg?height=100&width=300",
    linkUrl: "#",
    sponsor: "KBZ Bank",
  },
  {
    id: "3",
    title: "Myanmar Tea",
    description: "Authentic Laphet Yay since 1950",
    imageUrl: "/placeholder.svg?height=100&width=300",
    linkUrl: "#",
    sponsor: "Golden Tea Co.",
  },
]
